---

# Demo title
title: "Title"

# Application input configuration. This is a list of inputs
inputs:
    # Allowed sources of the input data. Allowed values
    # - camera                      [IMX390 Camera]
    # - <some_path>/directory       [Directory of Image]
    # - <some_path>/filename.nv12   [Image]
    #
    input0:
        # Camera Source
        source: camera

        # Sensor id -  by default set to imx390
        sen-id: imx390
  
        # Input data width
        width: 1920

        # Input data height
        height: 1080

        # This is the port number of fusion board the camera is connected to.
        camera-id: 0

        # VPAC id, needed only for devices with more than one VPAC to choose from (optional)
        vpac-id: 1

        # VISS DCC file path (optional)
        viss-dcc-path: /opt/imaging/imx390/dcc_viss_wdr.bin

        # LDC DCC file path (optional)
        ldc-dcc-path: /opt/imaging/imx390/dcc_ldc_wdr.bin

    input1:
        # Directory containing nv12 images of same resolution.
        source: /opt/edgeai-test-data/images/

        # Input data width
        width: 1280

        # Input data height
        height: 720

        # If file input need to be looped once all images are displayed.
        loop: True

    input2:
        # NV12 Image Source
        source: /opt/edgeai-test-data/images/0000.nv12

        # Input data width
        width: 1280

        # Input data height
        height: 720

        # If file input need to be looped
        loop: True

# Inference models. This is a list of models.
models:
    model0:
        # Path to the model
        model_path: /opt/model_zoo/ONR-SS-8610-deeplabv3lite-mobv2-ade20k32-512x512

        # Alpha value used for blending the sementic segmentation output
        alpha: 0.4

    model1:
        # Path to the model
        model_path: /opt/model_zoo/TFL-OD-2010-ssd-mobV2-coco-mlperf-300x300

        # Threshold for visualizing the output from the detection models
        viz_threshold: 0.6
  
    model2:
        # Path to the model
        model_path: /opt/model_zoo/TVM-CL-3090-mobileNetV2-tv

        # Number of classification results to pick from the top of the model output
        topN: 5

# Application output configuration. This is a list of outputs
outputs:
    # Allowed sink for the output. Allowed values
    # - display                   [Display]
    # - <some_path>/directory/    [Directory]
    # - <some_path>/filename.nv12 [Image]
    #
    output0:
        # Display on screen
        sink: display

        # Output display width
        width: 1920

        # Output display height
        height: 1080

    output1:
        # Save each frame in directory
        sink: /opt/edgeai-test-data/output/

        # Output display width
        width: 1920

        # Output display height
        height: 1080

    output2:
        # Save frame as single nv12 image
        sink: /opt/edgeai-test-data/output/output.nv12

        # Output display width
        width: 1920

        # Output display height
        height: 1080

flows:

    flow0: [input0,model0,output0,[0,480,640,480]]
    flow1: [input0,model0,output1]
    flow2: [input0,model1,output0,[640,480,640,480]]

    #################################################################################
    # flow: [*input*,*model*,*output*,[*pos_x*,*pos_y*,*width*,*height*](Optional)] #
    # input0,input1: Input(s) to use                                                #
    # model0,model1: Model(s) to be used (Same model can be share across as well)   #
    # output0,output1: Output(s) to be used.                                        #
    # If 4th argument i.e mosaic is not defined, it is assumed that no              #
    # mosaic will be used.                                                          #
    #                                                                               #
    #    # Display details for each output. The number of entries must match        #
    #    # the number of outputs using display                                      #
    #    #                                                                          #
    #    # *-------------------------------------------------------------------*    #
    #    # |                                                                   |    #
    #    # |d  pos_y|                          pos_y|                          |    #
    #    # |i       V        mosaic0                V         mosaic1          |    #
    #    # |s   --->*------------------------*  --->*------------------------* |    #
    #    # |p  pos_x|                        | pos_x|                        | |    #
    #    # |        |                        |      |                        | |    #
    #    # |h   480 |                        |      |                        | |    #
    #    # |e       |                        |      |                        | |    #
    #    # |i       |                        |      |                        | |    #
    #    # |g       *------------------------*      *------------------------* |    #
    #    # |h                 640                              640             |    #
    #    # |t                              disp width                          |    #
    #    # |                                                                   |    #
    #    # *-------------------------------------------------------------------*    #
    #    #                                                                          #
    #################################################################################