title: "Image Classification"
log_level: 2
inputs:
    input0:
        source: /opt/edgeai-test-data/raw_images/0000.nv12
        width: 1280
        height: 720
        loop: False
    input1:
        source: /opt/edgeai-test-data/raw_images/tiovx_apps
        width: 1280
        height: 720
        loop: False
models:
    model0:
        model_path: /opt/model_zoo/TFL-CL-0000-mobileNetV1-mlperf
        topN: 5
    model1:
        model_path: /opt/model_zoo/ONR-CL-6360-regNetx-200mf
        topN: 5
outputs:
    output0:
        sink: /opt/edgeai-test-data/output/output_image.nv12
        width: 1280
        height: 720
    output1:
        sink: /opt/edgeai-test-data/output/
        width: 1280
        height: 720

flows:
    flow0: [input1,model1,output1]
