title: "Image Classification"
log_level: 2
inputs:
    input0:
        source: /opt/edgeai-test-data/raw_images/tiovx_apps/0000.nv12
        width: 1280
        height: 720
        loop: True
    input1:
        source: /opt/edgeai-test-data/raw_images/tiovx_apps/
        width: 1280
        height: 720
        loop: True
models:
    model0:
        model_path: /opt/model_zoo/TFL-CL-0000-mobileNetV1-mlperf
        topN: 5
    model1:
        model_path: /opt/model_zoo/ONR-CL-6360-regNetx-200mf
        topN: 5
outputs:
    output0:
        sink: display
        width: 1920
        height: 1080
    output1:
        sink: /opt/edgeai-test-data/output/output_image.nv12
        width: 1920
        height: 1080
    output2:
        sink: /opt/edgeai-test-data/output/
        width: 1920
        height: 1080

flows:
    flow0: [input1,model1,output0,[320,180,1280,720]]