title: "Object Detection"
log_level: 2
inputs:
    input0:
        source: /opt/edgeai-test-data/raw_images/tiovx_apps/0000.nv12
        width: 1280
        height: 720
        loop: False
    input1:
        source: /opt/edgeai-test-data/raw_images/tiovx_apps
        width: 1280
        height: 720
        loop: False
models:
    model0:
        model_path: /opt/model_zoo/ONR-OD-8200-yolox-nano-lite-mmdet-coco-416x416
        viz_threshold: 0.6
    model1:
        model_path: /opt/model_zoo/ONR-OD-8020-ssd-lite-mobv2-mmdet-coco-512x512
        viz_threshold: 0.6
outputs:
    output0:
        sink: /opt/edgeai-test-data/output/output_image.nv12
        width: 1920
        height: 1080
    output1:
        sink: /opt/edgeai-test-data/output/
        width: 1920
        height: 1080

flows:
    flow0: [input1,model1,output1,[320,180,1280,720]]
