title: "Semantic Segmentation"
log_level: 2
inputs:
    input0:
        source: /opt/edgeai-test-data/raw_images/0001.nv12
        width: 1280
        height: 720
        loop: False
    input1:
        source: /opt/edgeai-test-data/raw_images/tiovx_apps
        width: 1280
        height: 720
        loop: False
models:
    model0:
        model_path: /opt/model_zoo/TFL-SS-2580-deeplabv3_mobv2-ade20k32-mlperf-512x512
        alpha: 0.4
    model1:
        model_path: /opt/model_zoo/ONR-SS-8710-deeplabv3lite-mobv2-cocoseg21-512x512
        alpha: 0.4
outputs:
    output0:
        sink: /opt/edgeai-test-data/output/output_image.nv12
        width: 1280
        height: 720
    output1:
        sink: /opt/edgeai-test-data/output/
        width: 1280
        height: 720

flows:
    flow0: [input1,model1,output1]